name: Run CI Checks

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  lint-kotlin:
    if: github.event.pull_request.draft == false
    name: Lint Kotlin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Lint Kotlin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lintKotlin

  lint-android:
    if: github.event.pull_request.draft == false
    name: Lint Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Lint Android
        uses: gradle/gradle-build-action@v2
        with:
          arguments: lint

  unit-tests:
    if: github.event.pull_request.draft == false
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 19

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
